### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by mindplay-dk** [tivac/rollup-plugin-sizes#10]
I can't get this to work - the plugin just errors out.

Looks like it's using an outdated API?

```
(!) rollup-plugin-sizes plugin: The ongenerate hook used by plugin rollup-plugin-sizes is deprecated. The generateBundle hook should be used instead.
[!] (rollup-plugin-sizes plugin) TypeError: details.bundle.modules.forEach is not a function
TypeError: details.bundle.modules.forEach is not a function
    at Object.ongenerate (/mnt/c/workspace/kodus-content-ui/node_modules/rollup-plugin-sizes/index.js:62:36)
    at /mnt/c/workspace/kodus-content-ui/node_modules/rollup/dist/rollup.js:16611:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Here's my `rollup.config.js`:

```js
import typescript from 'rollup-plugin-typescript2';
import postcss from 'rollup-plugin-postcss';
import { terser } from "rollup-plugin-terser";
import sizes from 'rollup-plugin-sizes';

export default [
    {
        input: "typescript/editor.ts",
        inlineDynamicImports: true,
        external: [
            "media",
            "content_lang",
        ],
        output: {
            file: "assets/js/editor.js",
            format: "amd",
            sourcemap: true,
        },
        plugins: [
            sizes(),
            postcss({
                extract: "assets/css/editor.css",
                sourceMap: true,
            }),
            typescript({
                typescript: require("typescript"),
                tsconfig: "typescript/tsconfig.json",
            }),
            terser()
        ]
    }
];
```

Have tried placing `sizes()` both first and last in the `plugins` list - it's the same error.

Installed package versions:

```
rollup-plugin-postcss@2.0.3
rollup-plugin-sizes@0.4.2
rollup-plugin-terser@4.0.3
rollup-plugin-typescript2@0.19.2
rollup@1.1.2
typescript@2.9.2
```

**Comment by mindplay-dk** [comment]
No problem, thanks for the update :-)
